# Generated by Django 3.1.3 on 2020-12-05 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=32)),
                ('product_detail', models.TextField(blank=True, max_length=1000, null=True)),
                ('product_image', models.ImageField(max_length=254, upload_to='document/')),
                ('product_price', models.CharField(default=1, max_length=32)),
                ('date', models.DateTimeField(null=True)),
                ('product_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BidDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.CharField(max_length=32)),
                ('bid_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginRegsiter.product')),
                ('bid_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
